[project]
name = "testflinger-deploy-regularly"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "requests>=2.32.3",
    "requests-oauthlib>=2.0.0",
    "temporalio>=1.11.1",
]
